server:
  port: 9100
# Eureka 注册中心服务的配置信息
eureka:
  instance:
    hostname: eureka9100.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka9101.com:9101/eureka/,http://eureka9102.com:9102/eureka/ # 集群配置，此处可以写多个注册中心地址